#!/usr/bin/env python3
"""Deterministic forensic reconstruction for the real MT5 portfolio run."""
from __future__ import annotations

import csv
import re
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "runs/reports/deployment_engine_v1/portfolio_equivalence_round2"
EVIDENCE = BASE / "evidence"
OUT = BASE
JOURNAL = EVIDENCE / "mt5_journal.log"
HTML = EVIDENCE / "ReportTester-1514758871_4.html"
PYTHON = BASE / "python_portfolio_trades.csv"
TS = re.compile(r"(\d{4}\.\d{2}\.\d{2} \d{2}:\d{2}:\d{2})")
DEAL = re.compile(r"deal #(\d+) (buy|sell) ([0-9.]+) EURUSD at ([0-9.]+) done \(based on order #(\d+)\)")
ORDER = re.compile(r"market (buy|sell) ([0-9.]+) EURUSD(?:, close #(\d+))?(?: sl: ([0-9.]+) tp: ([0-9.]+))?")
STRAT = re.compile(r"SQX_ORDER_SENT strategy=(SQX-[A-Za-z0-9-]+)")
POSCLOSE = re.compile(r"SQX_POSITION_CLOSE strategy=(SQX-[A-Za-z0-9-]+) TIME_EXIT")
TRIGGER = re.compile(r"(stop loss|take profit) triggered #(\d+) (buy|sell) [0-9.]+ EURUSD [0-9.]+ sl: ([0-9.]+) tp: ([0-9.]+) \[#(\d+) (buy|sell) [0-9.]+ EURUSD at ([0-9.]+)\]")

def stamp(line: str) -> str:
    m = TS.search(line)
    return m.group(1).replace('.', '-') if m else ''

def parse_journal():
    lines = JOURNAL.read_text(encoding='utf-16').splitlines()
    deals = {}
    entry_strategy = {}
    entry_meta = {}
    exits = {}
    pending_close = None
    time_logs = []
    close_events = []
    last_deal = None
    for line in lines:
        t = stamp(line)
        dm = DEAL.search(line)
        if dm:
            n, side, vol, price, order = dm.groups()
            d = {'deal_id': int(n), 'order_id': int(order), 'side': side, 'volume': float(vol), 'price': float(price), 'time': t}
            deals[int(order)] = d
            last_deal = int(order)
            if pending_close is not None:
                pending_close['exit_order'] = int(order)
                pending_close['exit_deal_id'] = int(n)
                pending_close['exit_price'] = float(price)
                pending_close['exit_time'] = t
                pending_close['exit_volume'] = float(vol)
                pending_close = None
        sm = STRAT.search(line)
        if sm and last_deal is not None:
            entry_strategy[last_deal] = sm.group(1)
        om = ORDER.search(line)
        if om:
            side, vol, close_no, sl, tp = om.groups()
            if close_no:
                pending_close = {'position_id': int(close_no), 'exit_time': t, 'exit_side': side, 'exit_volume': float(vol), 'exit_price': None, 'reason': 'TIME'}
                exits[int(close_no)] = pending_close
                close_events.append({'line_index': len(time_logs) + len(deals), 'timestamp': t, 'position_id': int(close_no)})
            elif sl is not None and last_deal is not None:
                entry_meta[last_deal] = {'entry_side': side, 'volume': float(vol), 'sl': float(sl), 'tp': float(tp)}
        tm = TRIGGER.search(line)
        if tm:
            reason, entry_no, entry_side, sl, tp, exit_no, exit_side, price = tm.groups()
            exits[int(entry_no)] = {'exit_time': t, 'exit_side': exit_side, 'exit_volume': None, 'exit_price': float(price), 'reason': 'STOP' if reason.startswith('stop') else 'TARGET', 'exit_order': int(exit_no)}
        pm = POSCLOSE.search(line)
        if pm:
            time_logs.append({'time': t, 'strategy_id': pm.group(1)})
    # Deal ordering gives the exact fill for both entry and exit order IDs.
    for no, ex in exits.items():
        # Stop/target entries have their exit order explicitly; time closes
        # were linked above to the next deal generated by the close request.
        if ex.get('exit_order') in deals:
            d = deals[ex['exit_order']]
            ex.update({'exit_deal_id': d['deal_id'], 'exit_price': d['price'], 'exit_time': d['time'], 'exit_volume': d['volume']})
    rows = []
    for order, sid in entry_strategy.items():
        if order not in deals or order not in entry_meta:
            continue
        d = deals[order]; m = entry_meta[order]; ex = exits.get(order, {})
        rows.append({'entry_order_id': order, 'entry_deal_id': d['deal_id'], 'strategy_id': sid, 'entry_time': d['time'], 'direction': 'LONG' if d['side']=='buy' else 'SHORT', 'volume': d['volume'], 'entry_price': d['price'], 'stop_price': m['sl'], 'target_price': m['tp'], 'exit_order_id': ex.get('exit_order',''), 'exit_deal_id': ex.get('exit_deal_id',''), 'exit_time': ex.get('exit_time',''), 'exit_price': ex.get('exit_price',''), 'exit_reason': ex.get('reason','UNMATCHED')})
    rows.sort(key=lambda x: (x['entry_time'], x['entry_order_id']))
    # Re-read line positions for an exact close-requester correlation.
    for idx, line in enumerate(lines):
        om=ORDER.search(line)
        if om and om.group(3):
            requester=''
            for nxt in lines[idx+1:idx+6]:
                pm=POSCLOSE.search(nxt)
                if pm and stamp(nxt)==stamp(line): requester=pm.group(1); break
            close_no=int(om.group(3)); owner=entry_strategy.get(close_no,'UNRESOLVED')
            d=deals.get(close_no,{})
            close_events.append({'timestamp':stamp(line),'position_id':close_no,'position_owner':owner,'position_entry_time':d.get('time',''),'requesting_strategy_id':requester})
    close_events=[x for x in close_events if 'position_owner' in x]
    return lines, rows, time_logs, deals, close_events

def html_rows():
    table = pd.read_html(HTML)[1]
    orders = []
    for _, r in table.iterrows():
        v = [str(x) for x in r.tolist()]
        if len(v) < 13 or not re.match(r"\d{4}\.\d{2}\.\d{2}", v[0]) or v[3] not in ('buy','sell') or '/' not in v[4]:
            continue
        vol = float(v[4].split('/')[0].replace(' ',''))
        orders.append({'time': v[0].replace('.', '-'), 'order_id': int(v[1]), 'symbol': v[2], 'side': v[3], 'volume': vol, 'sl': v[7] if v[7] != 'nan' else '', 'tp': v[8] if v[8] != 'nan' else '', 'status': v[11], 'comment': v[12] if v[12] != 'nan' else ''})
    return orders

def write_csv(path, rows, fields):
    with path.open('w', newline='') as f:
        w=csv.DictWriter(f, fieldnames=fields); w.writeheader(); w.writerows(rows)

def hours(a, b):
    x, y = pd.Timestamp(a), pd.Timestamp(b)
    if x.tzinfo is not None: x=x.tz_localize(None)
    if y.tzinfo is not None: y=y.tz_localize(None)
    return (x-y).total_seconds()/3600

def main():
    OUT.mkdir(parents=True, exist_ok=True)
    lines, trades, time_logs, deals, close_events = parse_journal()
    fields=list(trades[0]) if trades else []
    write_csv(OUT/'mt5_journal_trades.csv', trades, fields)
    html=html_rows()
    # Journal/HTML order-level reconciliation.
    hm={x['order_id']:x for x in html}
    jrows=[]
    for tr in trades:
        e=hm.get(tr['entry_order_id'],{}); x=hm.get(tr['exit_order_id'],{}) if tr['exit_order_id'] else {}
        jrows.append({'entry_order_id':tr['entry_order_id'],'exit_order_id':tr['exit_order_id'],'journal_strategy':tr['strategy_id'],'html_entry_comment':e.get('comment',''),'entry_time_match':tr['entry_time']==e.get('time',''),'entry_volume_match':tr['volume']==e.get('volume',''),'entry_sl_match':str(tr['stop_price'])==e.get('sl',''),'entry_tp_match':str(tr['target_price'])==e.get('tp',''),'html_exit_comment':x.get('comment',''),'exit_time_match':tr['exit_time']==x.get('time','')})
    write_csv(OUT/'journal_vs_html.csv',jrows,list(jrows[0]))
    py=pd.read_csv(PYTHON)
    # Chronological/strategy matching, with exact unmatched rows preserved.
    used=set(); comp=[]
    for _, p in py.iterrows():
        cand=[(i,m) for i,m in enumerate(trades) if i not in used and m['strategy_id']==p.strategy_id and m['direction']==p.direction]
        if cand:
            i,m=min(cand,key=lambda z:abs(pd.Timestamp(z[1]['entry_time']).value-pd.Timestamp(p.entry_time).value)); used.add(i); status='MATCHED'
        else: m={}; status='PYTHON_ONLY'
        comp.append({'strategy_id':p.strategy_id,'direction':p.direction,'python_entry_time':p.entry_time,'mt5_entry_time':m.get('entry_time',''),'entry_time_delta':hours(m['entry_time'],p.entry_time) if m else '','python_entry_price':p.entry_price,'mt5_entry_price':m.get('entry_price',''),'entry_price_delta':m.get('entry_price',0)-p.entry_price if m else '','python_stop':p.stop_price,'mt5_stop':m.get('stop_price',''),'stop_delta':m.get('stop_price',0)-p.stop_price if m else '','python_target':p.target_price,'mt5_target':m.get('target_price',''),'target_delta':m.get('target_price',0)-p.target_price if m else '','python_exit_time':p.exit_time,'mt5_exit_time':m.get('exit_time',''),'exit_time_delta':hours(m['exit_time'],p.exit_time) if m and m.get('exit_time') else '','python_exit_price':p.exit_price,'mt5_exit_price':m.get('exit_price',''),'python_exit_reason':p.exit_reason,'mt5_exit_reason':m.get('exit_reason',''),'status':status,'notes':''})
    for i,m in enumerate(trades):
        if i not in used: comp.append({'strategy_id':m['strategy_id'],'direction':m['direction'],'python_entry_time':'','mt5_entry_time':m['entry_time'],'entry_time_delta':'','python_entry_price':'','mt5_entry_price':m['entry_price'],'entry_price_delta':'','python_stop':'','mt5_stop':m['stop_price'],'stop_delta':'','python_target':'','mt5_target':m['target_price'],'target_delta':'','python_exit_time':'','mt5_exit_time':m['exit_time'],'exit_time_delta':'','python_exit_price':'','mt5_exit_price':m['exit_price'],'python_exit_reason':'','mt5_exit_reason':m['exit_reason'],'status':'MT5_ONLY','notes':''})
    write_csv(OUT/'trade_comparison.csv',comp,list(comp[0]))
    # Ownership evidence: each close order refers to the entry ticket it closed.
    ownership=[]
    for ev in close_events:
        ownership.append({'timestamp':ev['timestamp'],'requesting_strategy_id':ev.get('requesting_strategy_id',''),'expected_position':'strategy-selected ticket','actual_closed_position':ev['position_id'],'actual_position_owner':ev['position_owner'],'expected_time_exit_bars':'strategy definition','actual_holding_bars':'','ownership_match':ev.get('requesting_strategy_id')==ev['position_owner'],'status':'CROSS_STRATEGY_CLOSE' if ev.get('requesting_strategy_id')!=ev['position_owner'] else 'MATCH','notes':'CTrade.PositionClose(sym) is symbol-scoped; selected ticket was not passed.'})
    for log in time_logs:
        if not any(x['timestamp']==log['time'] and x['requesting_strategy_id']==log['strategy_id'] for x in ownership):
            ownership.append({'timestamp':log['time'],'requesting_strategy_id':log['strategy_id'],'expected_position':'strategy-selected ticket','actual_closed_position':'NONE_IN_JOURNAL','actual_position_owner':'NONE','expected_time_exit_bars':'strategy definition','actual_holding_bars':'','ownership_match':False,'status':'ORPHAN_TIME_EXIT_LOG','notes':'Repeated TIME_EXIT log without an associated close event.'})
    write_csv(OUT/'time_exit_ownership.csv',ownership,list(ownership[0]))
    print({'journal_lines':len(lines),'journal_deals':len(deals),'journal_entries':len(trades),'journal_time_logs':len(time_logs),'time_close_events':len(close_events),'html_orders':len(html),'python_trades':len(py),'python_only':sum(x['status']=='PYTHON_ONLY' for x in comp),'mt5_only':sum(x['status']=='MT5_ONLY' for x in comp)})

if __name__=='__main__': main()
