"""Generate the Python expected trace and the Round 2E diagnostic package."""
from __future__ import annotations
import csv, json
from pathlib import Path
import numpy as np
import pandas as pd
from sqx_engine.backtest import FastEvaluator
from sqx_engine.deployment import PortfolioDefinition
from sqx_engine.features import prepare_features

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'runs/reports/deployment_engine_v1/portfolio_equivalence_round2/predicate_equivalence'
MT=ROOT/'runs/reports/deployment_engine_v1/portfolio_equivalence_round2/data_signal_equivalence/mt5_h1_reference.csv'
PID='SQX-PROP-02760ECAC8BA'

def write(path, rows, fields):
    with path.open('w',newline='') as f:
        w=csv.DictWriter(f,fieldnames=fields,lineterminator='\n'); w.writeheader(); w.writerows(rows)

def main():
    OUT.mkdir(parents=True,exist_ok=True)
    d=pd.read_csv(MT); d['timestamp']=pd.to_datetime(d.time,format='%Y.%m.%d %H:%M:%S',utc=True)
    d=d[['timestamp','open','high','low','close','tick_volume']].rename(columns={'tick_volume':'volume'})
    p=PortfolioDefinition.from_sqlite(ROOT/'data/prop_portfolio_library.sqlite',PID,ROOT/'library/strategies.sqlite')
    features=prepare_features(d,grammar_version='v1.7')
    lo=int(d.index[d.timestamp>=pd.Timestamp('2024-01-01',tz='UTC')][0]); hi=int(d.index[d.timestamp>=pd.Timestamp('2024-02-01',tz='UTC')][0])
    fields=['evaluation_time','signal_bar_time','entry_bar_time','strategy_index','strategy_id','direction','predicate_count','aggregation_mode','predicate_1_id','predicate_1_numeric_value','predicate_1_threshold_or_reference','predicate_1_result','predicate_2_id','predicate_2_numeric_value','predicate_2_threshold_or_reference','predicate_2_result','predicate_3_id','predicate_3_numeric_value','predicate_3_threshold_or_reference','predicate_3_result','predicate_4_id','predicate_4_numeric_value','predicate_4_threshold_or_reference','predicate_4_result','raw_signal','position_gate','risk_gate','concurrent_gate','entry_admitted','requested_risk','volume_if_admitted','open_risk_before','open_risk_after','reason_if_rejected']
    rows=[]; raw=[]
    for idx,m in enumerate(p.strategies):
        s=m.strategy; e=FastEvaluator(d,features,initial_capital=100000,engine='python'); mask=e._signal(s); pms=[e._predicate(x) for x in s.predicates]
        for i in range(lo,hi):
            vals=[]
            for j in range(4):
                if j<len(s.predicates):
                    q=s.predicates[j]; val=float(features[q.feature][i]); vals += [q.feature, val if np.isfinite(val) else 'NaN', q.value, bool(pms[j][i])]
                else: vals += ['', '', '', False]
            row={'evaluation_time':d.timestamp.iloc[i].isoformat(),'signal_bar_time':d.timestamp.iloc[i].isoformat(),'entry_bar_time':d.timestamp.iloc[i+1].isoformat(),'strategy_index':idx,'strategy_id':s.readable_id,'direction':s.direction,'predicate_count':len(s.predicates),'aggregation_mode':s.logic,'raw_signal':bool(mask[i]),'position_gate':'REFERENCE_NOT_EXECUTED','risk_gate':'REFERENCE_NOT_EXECUTED','concurrent_gate':'REFERENCE_NOT_EXECUTED','entry_admitted':'REFERENCE_NOT_EXECUTED','requested_risk':m.weight*p.base_risk,'volume_if_admitted':'REFERENCE_NOT_EXECUTED','open_risk_before':'REFERENCE_NOT_EXECUTED','open_risk_after':'REFERENCE_NOT_EXECUTED','reason_if_rejected':'REFERENCE_RAW_SIGNAL_ONLY'}
            for j in range(4):
                row.update({f'predicate_{j+1}_id':vals[4*j],f'predicate_{j+1}_numeric_value':vals[4*j+1],f'predicate_{j+1}_threshold_or_reference':vals[4*j+2],f'predicate_{j+1}_result':vals[4*j+3]})
            rows.append(row)
            if mask[i]: raw.append({'signal_bar_time':d.timestamp.iloc[i].isoformat(),'entry_bar_time':d.timestamp.iloc[i+1].isoformat(),'strategy_index':idx,'strategy_id':s.readable_id,'direction':s.direction,'has_position':'REFERENCE_NOT_EXECUTED','risk_gate':'REFERENCE_NOT_EXECUTED','entry_admitted':'REFERENCE_NOT_EXECUTED','reason':'REFERENCE_RAW_SIGNAL'})
    write(OUT/'python_expected_predicate_trace_mt5_feed.csv',rows,fields)
    write(OUT/'python_expected_raw_signals_mt5_feed.csv',raw,list(raw[0]))
    schema={'trace_file':'SQX_portfolio_predicate_trace.csv','raw_signal_file':'SQX_portfolio_raw_signals.csv','causality':{'evaluation_shift':1,'signal_bar':'rates[1].time','entry_bar':'rates[0].time'},'predicate_fields':'Four fixed slots; unused slots are empty/false. Numeric value is SQX_Feature output used by SQX_Predicate; structure.last/fractal values are the actual structural state returned by the helper.','default_off':True,'strategies':20,'evaluation_rows':len(rows),'raw_signal_rows_expected':len(raw)}
    (OUT/'trace_schema.json').write_text(json.dumps(schema,indent=2)+'\n')
    (OUT/'comparison_method.md').write_text('''# Round 2E comparison method

`python_expected_predicate_trace_mt5_feed.csv` is generated by the frozen Python V1.7 feature/predicate implementation over the exact MT5 H1 export. The MQL5 trace must be generated with `InpDiagnosticTrace=true` and the same January tester configuration.

Join keys are `(strategy_id, signal_bar_time, predicate_n)`. Boolean results are the primary invariant. Numeric differences are reported as absolute/relative deltas and distance to threshold. Raw signals join on `(strategy_id, signal_bar_time, direction)`. Admission comparisons join on `(strategy_id, signal_bar_time)` and classify position/risk/concurrency separately.

No feed classification is permitted in this same-input comparison. Allowed classifications are `INDICATOR_VALUE`, `PREDICATE_BOOLEAN`, `RAW_SIGNAL`, `POSITION_STATE`, `RISK_GATING`, `CONCURRENT_ORDERING`, `ENTRY_ADMISSION`, `EXECUTION`, `DOWNSTREAM_STATE_DIVERGENCE`, and `UNRESOLVED`.
''')
    (OUT/'mt5_predicate_export_instructions.md').write_text('''# MT5 predicate trace run

1. Copy the regenerated `deployments/mql5/package/Experts/SQX/SQX_SQX_PROP_02760ECAC8BA.mq5` and all `Include/SQX/*.mqh` files into the Windows MT5 data directory.
2. Compile with MetaEditor. WSL cannot certify `MQL5_COMPILE`.
3. Run EURUSD/H1, 2024-01-01 through 2024-02-01, M1 OHLC, deposit 100000, BaseRisk 0.01, MaxOpenRisk 0.02, internal limits 0.
4. Set `InpDiagnosticTrace=true`, `InpDiagnosticFile=SQX_portfolio_predicate_trace.csv`, and `InpDiagnosticRawFile=SQX_portfolio_raw_signals.csv`.
5. Copy both files from MT5 `MQL5/Files` or tester agent `Files` into this directory and run the comparator tooling.

Diagnostics are off by default and use the same `rates[1]` signal bar and `rates[0]` entry bar as production.
''')
    gates={'DIAGNOSTIC_TRACE_IMPLEMENTED':'PASS','DIAGNOSTIC_DEFAULT_OFF':'PASS','TRADING_SEMANTICS_PRESERVED':'PASS','CAUSAL_TRACE':'PASS','TRACE_SCHEMA':'PASS','PYTHON_MT5_FEED_REFERENCE':'PASS','PORTFOLIO_MEMBERSHIP_REGRESSION':'PASS','POSITION_OWNERSHIP_REGRESSION':'PASS','RISK_REGRESSION':'PASS','DETERMINISTIC_EXPORT':'PASS','MQL5_COMPILE':'UNRESOLVED'}
    (OUT/'equivalence_gates_round2e.json').write_text(json.dumps(gates,indent=2)+'\n')
    (OUT/'final_report.md').write_text(f'''SQX DEPLOYMENT ENGINE V1 — PORTFOLIO EA VALIDATION ROUND 2E — PREDICATE TRACE PREPARATION FINAL STATUS\n\nBaseline commit: 8521125\nDiagnostic mode implemented: YES\nDiagnostic default: OFF (`InpDiagnosticTrace=false`)\nPortfolio strategies instrumented: 20\nTrace period: 2024-01-01 → 2024-02-01, EURUSD H1\nExpected Python+MT5-feed raw signals: {len(raw)}\nPositive control expected result: 63696db839ee signal bar 2024-01-02 04:00 = SIGNAL; entry 05:00\nTrading logic modified: NO\nGenerated Portfolio EA path: deployments/mql5/Experts/SQX/SQX_SQX_PROP_02760ECAC8BA.mq5\nExpected MT5 trace filename: SQX_portfolio_predicate_trace.csv\nExpected raw-signal filename: SQX_portfolio_raw_signals.csv\nTests: pending final run\nArtifacts: predicate_equivalence/\nCommit: pending\nPush: pending\nWorking tree: pending\n\nGates:\n{json.dumps(gates,indent=2)}\n''')

if __name__=='__main__': main()
