from __future__ import annotations
from abc import ABC, abstractmethod
from dataclasses import dataclass
import hashlib
import re
from pathlib import Path

from ..strategy import StrategyDefinition
from .models import PortfolioDefinition
from .templates import INDICATORS, PREDICATES, RISK, EXECUTION


class UnsupportedPredicateError(ValueError):
    code = "EXPORT_REJECT_UNSUPPORTED_PREDICATE"


SUPPORTED_PREDICATES = {
    "trend.close_ema", "trend.ema_slope", "trend.ema_pair", "trend.breakout_high", "trend.breakout_low",
    "rsi_14", "momentum.roc", "momentum.willr", "volatility.atr_regime", "volatility.bb_upper",
    "volatility.bb_lower", "volatility.bb_middle", "volatility.compression", "structure.last",
    "structure.break_high", "structure.break_low", "structure.fractal_high", "structure.fractal_low",
}

def predicate_key(feature: str) -> str:
    p = feature.split(".")
    return ".".join(p[:2]) if p[0] == "volatility" and p[1] in {"bb_upper", "bb_lower", "bb_middle", "compression", "atr_regime"} else ".".join(p[:2]) if p[0] in {"trend", "momentum", "structure"} else feature

def magic_number(identity: str) -> int:
    return 100000 + (int(hashlib.sha256(identity.encode()).hexdigest()[:8], 16) % 1900000000)

class DeploymentBackend(ABC):
    name = "abstract"
    @abstractmethod
    def export_strategy(self, strategy: StrategyDefinition, path: str | Path, **kwargs): ...
    @abstractmethod
    def export_portfolio(self, portfolio: PortfolioDefinition, path: str | Path, **kwargs): ...

@dataclass
class MQL5Backend(DeploymentBackend):
    name: str = "MQL5"

    def validate(self, strategy):
        for p in strategy.predicates:
            key = predicate_key(p.feature)
            if key not in SUPPORTED_PREDICATES:
                raise UnsupportedPredicateError(f"{UnsupportedPredicateError.code}: {p.feature}")
        if strategy.direction not in {"LONG", "SHORT"}: raise ValueError("Unsupported direction")

    def export_strategy(self, strategy, path, portfolio_id="", include_dir=None):
        self.validate(strategy); return _write_ea(strategy, None, Path(path), portfolio_id, include_dir)

    def export_portfolio(self, portfolio, path, include_dir=None):
        for x in portfolio.strategies: self.validate(x.strategy)
        return _write_ea(None, portfolio, Path(path), "", include_dir)


def _cpp_string(x): return str(x).replace('\\', '\\\\').replace('"', '\\"')
def _tf(x): return {"M15":"PERIOD_M15", "H1":"PERIOD_H1", "H4":"PERIOD_H4"}.get(x, f"PERIOD_{x}")

def _predicate_expr(p):
    return f'SQX_Predicate(rates, {p.feature!r}, "{p.operator}", {float(p.value):.17g}, shift)'

def _strategy_block(s, index):
    preds = [f'SQX_Predicate(rates, "{_cpp_string(p.feature)}", "{p.operator}", {float(p.value):.17g}, shift)' for p in s.predicates]
    join = " && " if s.logic == "AND" else " || "
    return f'''// {s.readable_id} canonical={s.canonical_hash}\n#define SQX_S{index}_ID "{_cpp_string(s.readable_id)}"\n#define SQX_S{index}_MAGIC {magic_number(s.canonical_hash)}\n#define SQX_S{index}_TF {_tf(s.timeframe)}\n#define SQX_S{index}_ATR_PERIOD {s.atr_period}\n#define SQX_S{index}_STOP_ATR {s.stop_atr:.17g}\n#define SQX_S{index}_TARGET_ATR {s.target_atr:.17g}\n#define SQX_S{index}_TIME_EXIT {s.time_exit}\n#define SQX_S{index}_DIRECTION_{s.direction} 1\nbool SQX_S{index}_Signal(const MqlRates &rates[], const int shift) {{ return ({join.join(preds)}) && SQX_ATR(rates, {s.atr_period}, shift) > 0; }}\n'''

def _write_ea(strategy, portfolio, path, portfolio_id, include_dir):
    path.parent.mkdir(parents=True, exist_ok=True)
    if include_dir is None: include_dir = path.parent.parent / "Include" / "SQX"
    include_dir = Path(include_dir); include_dir.mkdir(parents=True, exist_ok=True)
    _write_includes(include_dir)
    if strategy:
        blocks = _strategy_block(strategy, 0); strategies = [(strategy, 0)]
        title = f"SQX_{strategy.readable_id.replace('-', '_')}"
        body = _single_ea(strategy, blocks, portfolio_id)
    else:
        strategies = [(x.strategy, i) for i, x in enumerate(portfolio.strategies)]
        blocks = "\n".join(_strategy_block(s, i) for s, i in strategies)
        title = f"SQX_{portfolio.portfolio_id.replace('-', '_')}"
        body = _portfolio_ea(portfolio, blocks, strategies)
    body = _normalize_exit_translation(body, strategy, portfolio)
    # MQL5 exposes equity through AccountInfoDouble; ACCOUNT_EQUITY is an enum,
    # not a callable function. Keep this normalization at the exporter boundary
    # so every generated EA, including future portfolio layouts, gets valid code.
    body = body.replace("ACCOUNT_EQUITY()", "AccountInfoDouble(ACCOUNT_EQUITY)")
    path.write_text("// Generated by SQX Deployment Engine V1; do not edit.\n" + body)
    return path

def _normalize_exit_translation(body, strategy, portfolio):
    """Keep distance arguments to SQX_SendEntry in ATR-price units.

    The execution wrapper receives stop/target *distances* and converts them
    to broker price levels.  The frozen Python evaluator defines target as
    ATR(signal bar) * target_atr; it must not be multiplied by the already
    expanded stop distance.
    """
    body = re.sub(r"atr\*([0-9.e+-]+)/([0-9.e+-]+)\*stop", r"atr*\1", body)
    body = re.sub(r"SQX_S(\d+)_TARGET_ATR/SQX_S\1_STOP_ATR\*stop", r"SQX_S\1_TARGET_ATR", body)
    if strategy is not None:
        body = body.replace(
            "void OnTick() { static datetime last=0;",
            f"void OnTick() {{ SQX_ManagePosition(_Symbol,InpMagic,{_tf(strategy.timeframe)},{strategy.time_exit},InpPortfolioId,SQX_S0_ID); static datetime last=0;",
        )
    elif portfolio is not None:
        for i, item in enumerate(portfolio.strategies):
            needle = f"last[{i}]=iTime(_Symbol,SQX_S{i}_TF,0);{{ MqlRates r{i}[];"
            replacement = f"last[{i}]=iTime(_Symbol,SQX_S{i}_TF,0);{{ SQX_ManagePosition(_Symbol,SQX_S{i}_MAGIC,SQX_S{i}_TF,SQX_S{i}_TIME_EXIT,\"{_cpp_string(portfolio.portfolio_id)}\",SQX_S{i}_ID); MqlRates r{i}[];"
            body = body.replace(needle, replacement)
    return body

def _write_includes(directory):
    for name, body in (("sqx_indicators.mqh", INDICATORS), ("sqx_predicates.mqh", PREDICATES),
                       ("sqx_risk.mqh", RISK), ("sqx_execution.mqh", EXECUTION)):
        (directory / name).write_text(body)

def _header():
    return '#property strict\n#include <Trade/Trade.mqh>\n#include <SQX/sqx_indicators.mqh>\n#include <SQX/sqx_predicates.mqh>\n#include <SQX/sqx_risk.mqh>\n#include <SQX/sqx_execution.mqh>\n'

def _common_oninit(ids):
    return 'int OnInit() { SQX_Log("SQX_INIT", "", "", _Symbol, _Period, 0, 0, 0, 0, "NETTING_OR_HEDGING_ACCOUNT_MODE"); return INIT_SUCCEEDED; }\n'

def _single_ea(s, blocks, portfolio_id):
    d = 1 if s.direction == "LONG" else -1
    return _header() + f'''\ninput double InpRiskFraction={s.stop_atr and 0.01:.8f};\ninput long InpMagic={magic_number(s.canonical_hash)};\ninput string InpPortfolioId="{_cpp_string(portfolio_id)}";\n{blocks}\n{_common_oninit([s])}\nvoid OnTick() {{ static datetime last=0; datetime now=iTime(_Symbol,{_tf(s.timeframe)},0); if(now==last) return; last=now; MqlRates rates[]; if(!SQX_LoadRates(_Symbol,{_tf(s.timeframe)},rates,600)) return; int shift=1; if(!SQX_S0_Signal(rates,shift)) return; double atr=SQX_ATR(rates,{s.atr_period},shift); double stop=atr*{s.stop_atr:.17g}; double volume=SQX_RiskVolume(_Symbol,ACCOUNT_EQUITY(),InpRiskFraction,stop); SQX_RiskDecision decision=SQX_CheckPortfolioRisk(InpRiskFraction,InpRiskFraction,0.02); if(decision.action==SQX_REJECT) {{ SQX_Log("SQX_RISK_REJECT",InpPortfolioId,SQX_S0_ID,_Symbol,{_tf(s.timeframe)},0,volume,stop,InpRiskFraction,"RISK_LIMIT"); return; }} if(volume<=0) return; SQX_SendEntry(_Symbol,{"ORDER_TYPE_BUY" if d==1 else "ORDER_TYPE_SELL"},volume,stop,atr*{s.target_atr:.17g}/{s.stop_atr:.17g}*stop,InpMagic,InpPortfolioId,SQX_S0_ID); }}\n'''

def _portfolio_ea(p, blocks, strategies):
    calls = []
    for s, i in strategies:
        d = "ORDER_TYPE_BUY" if s.direction == "LONG" else "ORDER_TYPE_SELL"
        body = f'''{{ MqlRates r{i}[]; if(SQX_LoadRates(_Symbol,SQX_S{i}_TF,r{i},600) && SQX_S{i}_Signal(r{i},1)) {{ double atr=SQX_ATR(r{i},SQX_S{i}_ATR_PERIOD,1), stop=atr*SQX_S{i}_STOP_ATR; double requested=SQX_WEIGHTED_RISK({p.base_risk:.17g}, {dict((x.strategy.readable_id,x.weight) for x in p.strategies)[s.readable_id]:.17g}); SQX_RiskDecision rd=SQX_CheckPortfolioRisk(requested,requested,{p.max_open_risk:.17g}); if(rd.action==SQX_REJECT) SQX_Log("SQX_RISK_REJECT","{_cpp_string(p.portfolio_id)}",SQX_S{i}_ID,_Symbol,SQX_S{i}_TF,0,0,stop,requested,"RISK_LIMIT"); else {{ double v=SQX_RiskVolume(_Symbol,ACCOUNT_EQUITY(),rd.risk,stop); if(v>0) SQX_SendEntry(_Symbol,{d},v,stop,atr*SQX_S{i}_TARGET_ATR/SQX_S{i}_STOP_ATR*stop,SQX_S{i}_MAGIC,"{_cpp_string(p.portfolio_id)}",SQX_S{i}_ID); }} }} }}'''
        calls.append(f'if(iTime(_Symbol,SQX_S{i}_TF,0)!=last[{i}]){{last[{i}]=iTime(_Symbol,SQX_S{i}_TF,0);{body}}}')
    return _header() + f'''\ninput double InpBaseRisk={p.base_risk:.8f};\ninput double InpMaxOpenRisk={p.max_open_risk:.8f};\ninput double InpInternalDailyLimit=0.0;\ninput double InpInternalTotalLimit=0.0;\n{blocks}\n{_common_oninit([x.strategy for x in p.strategies])}\nvoid OnTick() {{ SQX_UpdatePropAccount(InpInternalDailyLimit,InpInternalTotalLimit); static datetime last[64]; int k=0; for(int i=0;i<{len(strategies)};i++) {{ datetime now=iTime(_Symbol,(i==i ? SQX_S{i}_TF : PERIOD_CURRENT),0); if(now==last[i]) continue; last[i]=now; }} for(int i=0;i<{len(strategies)};i++) {{ {calls[0] if len(calls)==1 else ''} }} }}\n'''.replace('for(int i=0;i<'+str(len(strategies))+';i++) { { '+(calls[0] if len(calls)==1 else '')+' } }', '\n'.join(calls)) if len(strategies)==1 else _portfolio_ea_impl(p, blocks, calls, strategies)

def _portfolio_ea_impl(p, blocks, calls, strategies):
    return _header() + f'''\ninput double InpBaseRisk={p.base_risk:.8f}; input double InpMaxOpenRisk={p.max_open_risk:.8f}; input double InpInternalDailyLimit=0.0; input double InpInternalTotalLimit=0.0;\n{blocks}\n{_common_oninit([x.strategy for x in p.strategies])}\nvoid OnTick() {{ static datetime last[64]; SQX_UpdatePropAccount(InpInternalDailyLimit,InpInternalTotalLimit);\n'''+"\n".join(calls)+"\n}\n"
